
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  ingest_data:
    image: taxi_ingest:v001
    environment:
      - USER=root
      - PASSWORD=root
      - HOST=host.docker.internal
      - PORT=5432
      - DB=ny_taxi
      - TABLE_NAME=yellow_taxi_trips 
    depends_on:
      - pgdatabase

